### ISSUE TITLE
Not compiling with kernel 3.2

### ISSUE THREAD

**Issue by moviemaniac** [cmcqueen/alim6117_wdt#1]
Hi
I am trying to compile this driver under debian squeeze with kernel 3.2, on an DMP 3300MX-A machine, but I am receiving the following output
# make

make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-0.bpo.4-486'
  LD      /home/administrator/wd/built-in.o
  CC [M]  /home/administrator/wd/alim6117_wdt.o
/home/administrator/wd/alim6117_wdt.c: In function ‘alim6117_init’:
/home/administrator/wd/alim6117_wdt.c:297: error: implicit declaration of function ‘watchdog_init_timeout’
/home/administrator/wd/alim6117_wdt.c:301: error: implicit declaration of function ‘watchdog_set_nowayout’
make[4]: *** [/home/administrator/wd/alim6117_wdt.o] Error 1
make[3]: *** [_module_/home/administrator/wd] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.2.0-0.bpo.4-486'
make: **\* [default] Error 2

Any help?
Plus I'd need some instructions on how to setup the driver properly alongside with the bios to get watchdog working as expected.

Thanks

**Comment by cmcqueen** [comment]
I haven't tried kernel 3.2—I'm using 3.16 myself and unlikely to go back.

It looks as though:
- `watchdog_set_nowayout` was added in kernel 3.3.
- `watchdog_init_timeout` was added in kernel 3.9.

In the repository, you'll see earlier commit 4ee605c344ed4b474e1609ea232fc9d36b8b2d55 in which I did a minimal update of the original code by Federico Bareilles. Try that and see if it works better for you. It was after that commit that I reworked the the driver to use the kernel watchdog API (including those two functions named above).

**Comment by cmcqueen** [comment]
On the DMP eBox 3300MX-A mini-PC, my experience indicates that you don't need to set up the watchdog in the BIOS, unless you want it to be running right from boot-up.

If it's not enabled in the BIOS, the watchdog will start running once an application opens the watchdog device `/dev/watchdog` and starts patting it through the watchdog API.

The watchdog module needs to be loaded at boot time. Normally you would do this by adding the driver name `alim6117_wdt` to a line in the file `/etc/modules`. The driver file `alim6117_wdt.ko` needs to be located in the right directory under `/lib/modules/` for the kernel. E.g. in my case, it's `/lib/modules/3.16.0-4-586/kernel/drivers/watchdog/alim6117_wdt.ko`.

If you do enable the watchdog in the BIOS, with a timeout such as 120 seconds, that means an application must open the watchdog driver and start patting the watchdog within 120 seconds of boot-up, or else the system will be reset. This might resolve a potential occasional lock-up at boot time. But it might also be risky, if boot-up ever takes longer than nominal, for example if Linux decides to do a hard disk scan-and-repair at boot time.

**Comment by cmcqueen** [comment]
By the way, you might consider running Debian 8.4 on your DMP eBox 3300MX-A. That's what I'm using, and it comes with the 3.16 kernel.

**Comment by moviemaniac** [comment]
Dear cmcqueen,
thanks for your reply. I will try your older driver version. But I would like to do a couple of tests based on what you suggested.

First of all let me say that I set up the bios watchdog to 512 secs to avoid problems due to longer boot up.

If I do like you suggest, disable the BIOS watchdog and load just the module at startup, what would be the situation? It would be a software watchdog, pretty much like the softdog? So if the system hangs or freezes lets say for a kernel panic, it won't reboot becouse there won't be no hardware reset, right?

Thanks for your help

**Comment by moviemaniac** [comment]
I've downloaded the branch you suggested, I've edited my Makeinstall script this way

```
obj-m += alim6117_wdt.o

PWD  := $(shell pwd)
KDIR := /lib/modules/$(shell uname -r)/build

default:
    make -C $(KDIR) M=$(PWD) modules
install: default
    make INSTALL_MOD_DIR=kernel/drivers/watchdog -C $(KDIR) M=$(PWD) modules_install
clean:
    make -C $(KDIR) M=$(PWD) clean
```

Now the module gets installed directly in the path you suggested
Then I've loaded the module, added it to the /etc/modules file, then enabled the watchdog in the /etc/watchdog.conf file.
Then I rebooted, and the system keeps rebooting in a loop. To stop it, I need to disable watchdog in /etc/watchdog.conf.

Now I have the module alim6117_wdt properly loaded at boot time, if I run
`# dmesg | grep ali`

I get this output

`[   26.910735] WDT driver for ALi M6117 v(0.2.0) initialising.`

while `# lsmod` says

`alim6117_wdt           12565  0`

I can't enable watchdog thoug, in the /etc/watchdog.conf otherwise the systemn reboots in a loop.

ODD thing: the configuration right now is:
1) BIOS watchdog disabled
2) device = /dev/watchdog in /etc/watchdog file is commented, so disabled
3) alim6117_wdt module loaded at boot time (dmesg | grep ali returns WDT driver for ALi M6117 v(0.2.0) initialising)

so the watchdog should be disabled, right?
But if I run # ls -alh /dev/watchdog
I get
crw------- 1 root root 10, 130 Jun 10 15:43 /dev/watchdog
so the watchdog is enabled and up since 15:43 (but I run the command at 16:02, just in case it matters)

If I run
`# ps -A | grep watchdog`
I sometimes get an output like
    6 ?        00:00:00 watchdog/0
 1317 ?        00:00:01 watchdog

sometimes like
    6 ?        00:00:00 watchdog/0
 1317 ?        00:00:01 watchdog
 2733 ?        00:00:00 watchdog <defunct>

So it means that something is going on with the watchdog, right?

I am quite frustrated at the moment.

**Comment by cmcqueen** [comment]
It sounds as though you're doing well. It sounds as though the watchdog module is installed correctly and loading correctly.

Now, it seems that you just need to work out the right configuration of the watchdog _application_ (which is controlled by `/etc/watchdog.conf`) to monitor the system the way you want it to.

Just to be clear, the `alim6117_wdt` watchdog driver just provides a standard Linux API for enabling/disabling and patting the watchdog. Once that is in place, you need to have an application in the system to open the watchdog driver and pat the watchdog according to some criteria of "system operating normally", which you have to decide. It sounds as though you've installed the application which is (funnily enough) named `watchdog` and is configured with `/etc/watchdog.conf`. That application has configurable checks it can do to decide whether the system is "operating normally". As long as it is happy with those checks, then it will pat the watchdog. If any of the configured checks fail, then it will not pat the watchdog, resulting in a system reset. Now you need to go through the configuration in that file, and decide what that watchdog application will monitor to determine the "system operating normally" criterion. That can be monitoring that certain applications are running (by checking their PID files, typically somewhere under `/var/run/`), or monitoring that a network connection is operating normally, or a variety of other criterion.

You're not obligated to use that watchdog application. Alternatively you could write your own if you have some other way to determine that the system is operating normally. Maybe if your system is intended to run one main application that you wrote, you could add code to your application to pat the watchdog itself as long as it is running normally. That's your choice.

Does that sound okay?

**Comment by moviemaniac** [comment]
So it seems that I was somewhat misleaded by my readings. 
Particularly, installing the driver and the watchdog.deb packet won't resolve my problem.
Installing the driver is the first step.
Enabling an application (which could be one I developed or the standard watchdog.deb) is the second step.
Then it is not enough to enable the /dev/watchdog in the /etc/watchdog.conf file, I need to activate at least one check (against internet connection for example).

This is a software watchdog though. I mean, if the system hangs for a kernel panic, it won't reboot, right?
That is why I thought of enabling even the hardware watchdog, so that the system can be reset in case of kernel panic or freezes.

Am I wrong?

**Comment by cmcqueen** [comment]
What you said sounded good, apart from the last paragraph. The `alim6117_wdt` driver is for enabling and patting the hardware watchdog. The `watchdog` application implements a sort of higher-level software watchdog, which means it can check high-level operation (e.g. of applications and network interfaces). But the `watchdog` application does enable and pat the hardware watchdog through the driver. As long as everything is okay, the `watchdog` application pats the hardware watchdog (at an interval of half the hardware watchdog timeout I think). If there is a system hang (e.g. due to kernel panic), then the `watchdog` application will no longer be patting the hardware watchdog, so the hardware watchdog _will_ reset the system.

Note, if the `watchdog` application shuts down normally, then it usually disables the hardware watchdog. If you want to ensure that the `watchdog` application can't accidentally disable the hardware watchdog, then you can enable the `nowayout` option in the driver. I can't remember exactly, but you should be able to do that by adding `nowayout=1` to the module load line in `/etc/modules`. But double-check that.
